Added files for second homework
FlameNV/AltexSoft-Homeworks pull request #2
Opened 2021-06-09 11:45 UTC by FlameNV

2021-06-11 00:18 UTC, Korew requested changes
There is no need to give too precise names for classes - use more general ones, since sections / cards / buttons and other elements can often be reused in different places.

Your site looks pretty normal on mobile and desktop (1440px or more). But in the middle - not so good:
![image](https://user-images.githubusercontent.com/17281920/121612262-b956a080-ca62-11eb-867e-a5ec75861616.png)

Add gap here:
![image](https://user-images.githubusercontent.com/17281920/121612317-d68b6f00-ca62-11eb-8f0e-c62a2593d433.png)

Use center mode for slider:
![image](https://user-images.githubusercontent.com/17281920/121612347-e7d47b80-ca62-11eb-9615-ed93d69f1d7c.png)

When I swipe slides on my phone - they react to hover state:
![image](https://user-images.githubusercontent.com/17281920/121612591-57e30180-ca63-11eb-98d8-dd9c728b5948.png)

Selectors are too long:
![image](https://user-images.githubusercontent.com/17281920/121612664-819c2880-ca63-11eb-94ed-836a083627fb.png)

2021-06-11 00:18 UTC, Korew commented on AltexSoft lab 2/index.html
> +          <a href="#start" id="logo-dark">
You don't need two links - better just change image inside `<a>`.

Also you can use css property `filter: invert(1);` (change value can be from `0` to `1`, for example `.75`) for image - [read more](https://developer.mozilla.org/en-US/docs/Web/CSS/filter-function/invert()).

Best way - you could use css and change `fill` for it inside css.

2021-06-11 00:18 UTC, Korew commented on AltexSoft lab 2/index.html
> +          <button class="menu-btn" id="menu-btn" onclick="openMenu()">
![image](https://user-images.githubusercontent.com/17281920/121593636-d1b7c280-ca44-11eb-9880-4d1d238524c1.png)
Minimum recommended size for buttons you can tap with your finger is 44*44 pixels (there can be exceptions). You can set size for this button and but you can leave lines with current size and position them inside button. It is not strict - but every time you work on the site you have to keep in mind how users will interact with it.

_Just recommendation_

2021-06-11 00:18 UTC, Korew commented on AltexSoft lab 2/index.html
> +            <span class="menu-icon"></span>
`menu-icon` - useless class here.
```
<span></span>
<span></span>
<span></span>
```
Much more clean code. In css use `.menu-btn span` selector

_Just recommendation_

2021-06-11 00:18 UTC, Korew commented on AltexSoft lab 2/index.html
> +        <h1 class="header-title">Find trouble before trouble finds you.</h1>
`h1` can be only one on page. Cause you have only one page on entire the site - it is unnecessary  to give class name to h1.

But remember that if there are internal pages on the site, the headers there may look different and then the class names can be added.

_Just recommendation_

2021-06-11 00:18 UTC, Korew commented on AltexSoft lab 2/index.html
> +            SKOUT is a cybersecurity company that delivers total protection for
![image](https://user-images.githubusercontent.com/17281920/121596159-c619cb00-ca47-11eb-980a-f2640d5f8c20.png)
This text should be `20px` - please check all other content on your site

2021-06-11 00:18 UTC, Korew commented on AltexSoft lab 2/index.html
> +    <div class="container" id="start">
Why do you need this wrapper? No styles for `.container` class. id can be moved to header.

2021-06-11 00:18 UTC, Korew commented on AltexSoft lab 2/index.html
> +      <main class="main-section">
Bad class name. This is main content of your site and you have several sections inside. So why you name it `-section`?

Actually I saw styles for `.main-section` - they are useless. If you remove them - nothing will change.

2021-06-11 00:18 UTC, Korew commented on AltexSoft lab 2/index.html
> +            <h2 class="what-is-skout-title">What is SKOUT?</h2>
Bad class name - you have at least 5 titles that look almost same (only alignment can be different) - so you need to create one class name, for example `.section-title` and use it everywhere.

2021-06-11 00:18 UTC, Korew commented on AltexSoft lab 2/index.html
> +        <div class="cybersecurity-section">
Here you use `-section` in class name. In previous section no. Please be consistent

2021-06-11 00:18 UTC, Korew commented on AltexSoft lab 2/index.html
> +              <div class="marquee">
I do not understand at all what `marquee` means

2021-06-11 00:18 UTC, Korew commented on AltexSoft lab 2/index.html
> +              <span class="card-note-icon">i</span>
There is no need to place `i` in html - use `::before` selector with `content: 'i'` in css

2021-06-11 00:18 UTC, Korew commented on AltexSoft lab 2/index.html
> +                  <use xlink:href="./images/pictures.svg#security-img-1"></use>
Do not use `xlink:href` anymore. It is outdated format

2021-06-11 00:18 UTC, Korew commented on AltexSoft lab 2/index.html
> +                  <p class="skout-plans-card-item-name">Email</p>
Too long class names. This code difficult to read and it is very "noisy"
![image](https://user-images.githubusercontent.com/17281920/121601859-2ceeb280-ca4f-11eb-90b4-8a7897cb11d4.png)

2021-06-11 00:18 UTC, Korew commented on AltexSoft lab 2/index.html
> +                  src="./images/tusk.png"
`./images...` usually not used in html. 

`src="images/tusk.png"` would work same way

https://www.w3schools.com/html/html_filepaths.asp

2021-06-11 00:18 UTC, Korew commented on AltexSoft lab 2/index.html
> +              <a href="#">
Very strange clickable area :)
![image](https://user-images.githubusercontent.com/17281920/121602486-07ae7400-ca50-11eb-8443-f8bd6911a4d1.png)

2021-06-11 00:18 UTC, Korew commented on AltexSoft lab 2/index.html
> +      type="text/javascript"
no need to use `type="text/javascript"` anymore. Please remove

2021-06-11 00:18 UTC, Korew commented on AltexSoft lab 2/index.html
> +    <script src="./js/marquee.js"></script>
Better to concatenate all js in one file

2021-06-11 00:18 UTC, Korew commented on AltexSoft lab 2/js/hamburger.js
> +const menu = document.querySelector("#menu");
use `document.getElementById` when selecting by ID.

2021-06-11 00:18 UTC, Korew commented on AltexSoft lab 2/js/hamburger.js
> +const header = document.querySelector("#navigation");
Use single quotes for all strings in JS.

You can use double quotes, but single are used most often. Plus you used single in other places.

2021-06-11 00:18 UTC, Korew commented on AltexSoft lab 2/js/hamburger.js
> +  if (window.innerWidth < 1440) {
`window.innerWidth` and media-query in css are different. Please, use [matchMedia](https://developer.mozilla.org/ru/docs/Web/API/Window/matchMedia)

2021-06-11 00:18 UTC, Korew commented on AltexSoft lab 2/index.html
> +        <div class="header-nav" id="navigation">
You can add background to header after scroll
![image](https://user-images.githubusercontent.com/17281920/121603254-24977700-ca51-11eb-9a8e-646c6a079fac.png)

2021-06-11 00:18 UTC, Korew commented on AltexSoft lab 2/js/hamburger.js
> +function openMenu() {
bad name - this function can not only open menu, but close too,

2021-06-11 00:18 UTC, Korew commented on AltexSoft lab 2/js/hamburger.js
> +    if (this.scrollY) {
You've used arrow function (line 12) - it doesn't have `this` scope. So `this` points to `window` object. This is just a luck, that this code worked. You can use `window.scrollY` or you can change arrow function to regular one ([read more](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions))

2021-06-11 00:18 UTC, Korew commented on AltexSoft lab 2/js/hamburger.js
> +let navLinksLi = menu.getElementsByClassName("menu-item");
variable never reassigned. Use `const`

2021-06-11 00:18 UTC, Korew commented on AltexSoft lab 2/js/hamburger.js
> +    this.className += " active";
use [classList ](https://developer.mozilla.org/ru/docs/Web/API/Element/classList)to add/remove classes

2021-06-11 00:18 UTC, Korew commented on AltexSoft lab 2/js/hamburger.js
> +    current[0].className = current[0].className.replace(" active", "");
This is not the best solution. If there were `active` class for another element somewhere before menu links (and this is pretty general name - another developer could add it somewhere and you code will stop working and it will be very difficult to understand why)

Algorithm is very simple - after clicking on link you remove `active` class from all links in nav and than add this class to the link you just clicked.

2021-06-11 00:18 UTC, Korew commented on AltexSoft lab 2/js/marquee.js
> +const icon = document.querySelectorAll(".card-note-icon");
You selecting all icons, so `icons` would be better name for this const

2021-06-11 00:18 UTC, Korew commented on AltexSoft lab 2/js/marquee.js
> +const marquee = document.querySelectorAll('.marquee');
Be consistent - do not mix single and double quotes. Use single everywhere in js.

2021-06-11 00:18 UTC, Korew commented on AltexSoft lab 2/js/marquee.js
> +    marquee[index].style.display = 'block';
You've selected `marquee` all over the site. If somehow another element with same class name will appear in document - your code will stop working.

First you select section with cards:
`const cybersecurityCards = document.querySelector('.cybersecurity-cards-wrapper');` 
After this you can select elements inside this cards:
`const icon = cybersecurityCards.querySelectorAll('.card-note-icon');`
same for `marquee` (I already mentioned in html - I do not understand what this word means 🤷‍♂️)

2021-06-11 00:18 UTC, Korew commented on AltexSoft lab 2/js/slider.js
> +  responsive: [
slick has `mobileFirst` option. Cause you have to use mobile first approach, you need to apply this option for slick too

2021-06-11 00:18 UTC, Korew commented on AltexSoft lab 2/scss/_mixins.scss
> +  line-height: 24px;
Why do you use variable for font and just value for line-height?

You can set line height relative to font-size. For example `line-height: 1.5;` (actually it is 1.5 in most places according to design in Figma - so can be added globally and overwritten where needed)

2021-06-11 00:18 UTC, Korew commented on AltexSoft lab 2/scss/_mixins.scss
> +  font-family: $font-family-acme;
Why do you specify font here and for `letters-xs` you didn't do this?

I'm not sure it is good idea to add font-family here. You have to find main font of the site and set it globally (for `body`). Than you add font-family only for elements that use different font.

2021-06-11 00:18 UTC, Korew commented on AltexSoft lab 2/scss/style.scss
> +      top: 61px;
Why 61px? You set height 100vh and then moved whole nav down for 61px. This means bottom 61 pixels are hidden.

PS I understand you tried to compensate header height - but it is not the best solution, couse header height can be changed (actually this already happened - I see it's about 65 pixels now)

2021-06-11 00:18 UTC, Korew commented on AltexSoft lab 2/scss/style.scss
> +      .menu-login-btn {
this buttons almost similar - you had to create one class and add it to both buttons.

Actually almost all buttons are similar - I recommend to create class `.btn` and create couple modifications (for example `.btn-outlined`, `.btn-white`)

2021-06-11 00:18 UTC, Korew commented on AltexSoft lab 2/scss/style.scss
> +@import "media-query";
Much more easier to understand code, when media-queries are added right inside block.

For example:
```
.header {
  padding: 12px 0;

  @media screen and (min-width: 992px) {
    padding: 24px 0;
  }
}
```

2021-06-11 00:18 UTC, Korew commented on AltexSoft lab 2/scss/style.scss
> +.header {
It's better to split scss code to different files
_header.scss
_sections scss
etc

Names just examples - you have to create your own files.

2021-06-11 00:18 UTC, Korew commented on AltexSoft lab 2/scss/style.scss
> +        transition: 0.7s;
please, specify properties that will be animated.

2021-06-11 00:18 UTC, Korew commented on AltexSoft lab 2/scss/style.scss
> +            width: $size-dot;
6*6px - very small size. It will be almost impossible to tap on it with a finger.

![image](https://user-images.githubusercontent.com/17281920/121610979-e81f4780-ca5f-11eb-8b67-1e33ebd1c6f0.png)

2021-06-11 00:18 UTC, Korew commented on AltexSoft lab 2/scss/style.scss
> +              line-height: 24px;
Most often, line-height is not needed if the text fits on one line.

2021-06-11 00:18 UTC, Korew commented on AltexSoft lab 2/scss/_media-query.scss
> +@media only screen and (min-width: $size-desktop-width) {
You have only one media-query and 1440px - very strange size...

Almost all sections are 1200px width (1170px + 15px padding on the left and right). So definitely for desktop would be better to use `min-width: 1200px`.

But also you could add some more media-queries for smaller screens. Please open bootstrap (or any other popular css framework) and see what [breakpoints](https://getbootstrap.com/docs/4.1/layout/overview/) they use. Probably you won't need all of them in this project, but at least one more I recommend to add.

2021-06-11 00:18 UTC, Korew commented on AltexSoft lab 2/scss/_media-query.scss
> +          .solve-slider-item {
if you use scss this could be `&-item {`

2021-06-12 14:03 UTC, FlameNV commented on AltexSoft lab 2/index.html
> +    <script src="./js/marquee.js"></script>
Create one file and import it into this file? Or cut and paste all code in one file?

2021-06-12 15:30 UTC, FlameNV commented on AltexSoft lab 2/scss/style.scss
> +        transition: 0.7s;
This transition animates the menu button (switch cross to a burger and back)

2021-06-15 18:03 UTC, Korew approved these changes
Too "deep" selectors in css

Plans section not aligned on desktop:
![image](https://user-images.githubusercontent.com/17281920/122101405-ed441400-ce1c-11eb-9da5-939046b9b898.png)


Plans section overlaps previous section:
![image](https://user-images.githubusercontent.com/17281920/122101485-064cc500-ce1d-11eb-8123-4fbc6e927373.png)

Much more better - all comments are resolved.

2021-06-15 18:03 UTC, Korew commented on AltexSoft lab 2/index.html
> +                <a href="#" class="nav-link active">why skout</a>
You can write words starting with capital letter :)
Why Skout? (Skout - name of company, as I understand)

2021-06-15 18:03 UTC, Korew commented on AltexSoft lab 2/index.html
> +              get skout
Get Skout

2021-06-15 18:03 UTC, Korew commented on AltexSoft lab 2/index.html
> +        <div class="description-section">
There is html5 tag `<section>` - it is very suitable for sections :)

2021-06-15 18:03 UTC, Korew commented on AltexSoft lab 2/js/main.js
> +const menu = document.getElementById("menu");
Better use single quotes in js. It doesn't matter, but when you'll work on real project in a team - all of you will use same quotes. And they will be single :)

2021-06-15 18:03 UTC, Korew commented on AltexSoft lab 2/js/main.js
> +      header.classList.add("is-scroll");
You do not need to add class to 3 elements. Add class to whole header and change styles for these elements based on header class.

2021-06-15 18:03 UTC, Korew commented on AltexSoft lab 2/js/main.js
> +  if (window.matchMedia("(max-width: 1023px)").matches) {
in mobile first you use min-width, so better use it in js too. Just for consistency 
(add `!` to invert value)

2021-06-15 18:03 UTC, Korew commented on AltexSoft lab 2/js/main.js
> +      loginBtn.classList.add("is-scroll");
same

2021-06-15 18:03 UTC, Korew commented on AltexSoft lab 2/js/main.js
> +  }
24 lines of code:
```
  if (window.matchMedia("(max-width: 1023px)").matches) {
    if (window.scrollY) {
      logo.classList.add("is-scroll");
      menuIcon.classList.add("is-scroll");
      header.classList.add("is-scroll");
    } else {
      logo.classList.remove("is-scroll");
      menuIcon.classList.remove("is-scroll");
      header.classList.remove("is-scroll");
    }
  } else {
    if (window.scrollY) {
      logo.classList.add("is-scroll");
      header.classList.add("is-scroll");
      menu.classList.add("is-scroll");
      getSkoutBtn.classList.add("is-scroll");
      loginBtn.classList.add("is-scroll");
    } else {
      logo.classList.remove("is-scroll");
      header.classList.remove("is-scroll");
      menu.classList.remove("is-scroll");
      getSkoutBtn.classList.remove("is-scroll");
      loginBtn.classList.remove("is-scroll");
    }
  }
```
can be replaced:
```
    if (window.scrollY) {
      header.classList.add('is-scroll');
    } else {
      header.classList.remove('is-scroll');
    }
```

2021-06-15 18:03 UTC, Korew commented on AltexSoft lab 2/scss/_companies-section.scss
> +      display: flex !important;
If you use `!important` - probably you did something wrong.

2021-06-15 18:03 UTC, Korew commented on AltexSoft lab 2/scss/_companies-section.scss
> +      padding-bottom: 20px;
You can add media-queries right here:
```
@media only screen and (min-width: $size-laptop-large-size) {
  display: flex;
  align-items: center;
}
```

2021-06-15 18:03 UTC, Korew commented on AltexSoft lab 2/scss/_companies-section.scss
> +      .company-slide {
Do you use `.company-slide` outside `.companies-section` and `.companies-slider`?

```
.companies-section {
  .companies-slider {
```
This is useless here

2021-06-15 18:03 UTC, Korew commented on AltexSoft lab 2/scss/_contact-section.scss
> +    .contact-info {
same - you do not need `.contact-wrapper`.

And please, use advantages of scss
```
.contact {
  &-section {
    ...
  }
  &-info {
    ...
  }
}
```

2021-06-15 18:03 UTC, Korew commented on AltexSoft lab 2/scss/_contact-section.scss
> +        text-align: start;
You don't have rtl version here - this property useless.

2021-06-15 18:03 UTC, Korew commented on AltexSoft lab 2/scss/_contact-section.scss
> +            width: $size-arrow-right;
Don't create too many constant. Here it would be better to see size, not constant

2021-06-15 18:03 UTC, Korew commented on AltexSoft lab 2/scss/_contact-section.scss
> +}
Six closing brackets `}` means that code will be difficult to read and understand :)

2021-06-15 18:03 UTC, merged